import React, { useEffect, useState } from 'react';
import { ArrowUpRight, RefreshCw, LayoutDashboard, ShoppingBag, BookOpen, Calendar, Settings, LogOut, Heart } from 'lucide-react';
import { DashboardData, UserRole, Product } from '../types/index';
import { api } from '../services/api';
import { useApp } from '../context/AppContext';
import { ProductCard } from '../components/ProductCard';
import { AdminDashboardPage } from './AdminDashboardPage';

const roleNames: Record<UserRole, string> = { CUSTOMER: 'My wardrobe', STUDENT: 'Learning studio', INSTRUCTOR: 'Teaching studio', ADMIN: 'Business overview' };
const formatDate = (value: string) => new Date(value.includes('T') ? value : value + 'T12:00:00').toLocaleDateString('en-NG', { day: 'numeric', month: 'short', year: 'numeric', timeZone: 'Africa/Lagos' });
const money = (value: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(value);
export const DashboardPage: React.FC<{ role?: string; onNavigate: (route: string) => void }> = ({ role: requested, onNavigate }) => {
  const { user, authReady, wishlist, signOut, showToast } = useApp();
  const preferred = (['ADMIN', 'INSTRUCTOR', 'STUDENT', 'CUSTOMER'] as UserRole[]).find(r => user?.roles.includes(r));
  const role = (requested?.toUpperCase() || preferred || 'CUSTOMER') as UserRole;
  const allowed = !!user?.roles.includes(role);
  const [data, setData] = useState<DashboardData | null>(null);
  const [saved, setSaved] = useState<Product[]>([]);
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(true);
  const [tab, setTab] = useState('overview');
  const [revision, setRevision] = useState(0);
  const [busyId, setBusyId] = useState('');
  useEffect(() => { setTab('overview'); }, [role, user?.id]);
  useEffect(() => {
    let live = true;
    setData(null); setError(''); setLoading(true);
    if (!allowed) { setLoading(false); return; }
    Promise.all([api.getDashboard(role), role === 'CUSTOMER' ? api.getProducts() : Promise.resolve({ products: [] })]).then(([result, catalog]) => {
      if (live) { setData(result); setSaved(catalog.products.filter(p => wishlist.includes(p.id))); }
    }).catch(err => { if (live) setError(err.message); }).finally(() => { if (live) setLoading(false); });
    return () => { live = false; };
  }, [role, user?.id, allowed, revision, wishlist]);
  if (!authReady) return <div className="dashboard-message">Opening your account...</div>;
  if (!user) return <div className="dashboard-message"><h1>Your atelier awaits.</h1><p>Sign in to access your dashboard.</p><button className="brand-button" onClick={() => onNavigate('/login')}>Sign in <ArrowUpRight size={17} /></button></div>;
  if (!allowed) return <div className="dashboard-message"><h1>This is a different workspace.</h1><p>Your account does not have access to this role.</p><button className="brand-button" onClick={() => onNavigate('/dashboard')}>My dashboard <ArrowUpRight size={17} /></button></div>;
  const tabs = role === 'CUSTOMER' ? [['overview','Overview'],['orders','My orders'],['saved','Saved pieces']] : role === 'STUDENT' ? [['overview','Overview'],['learning','My courses'],['schedule','My schedule'],['certificates','Certificates']] : role === 'INSTRUCTOR' ? [['overview','Overview'],['teaching','My courses'],['schedule','Teaching schedule']] : [['overview','Overview'],['manage','Management']];
  const titles: Record<UserRole, string> = { CUSTOMER: 'Style, on your terms.', STUDENT: 'Keep your creativity moving.', INSTRUCTOR: 'Pass the craft forward.', ADMIN: 'The whole atelier, in view.' };
  const upcoming = data?.classes.filter(c => (c.status === 'SCHEDULED' || c.status === 'IN_PROGRESS') && c.date >= new Date().toLocaleDateString('en-CA', { timeZone: 'Africa/Lagos' })) || [];
  const stats = !data ? [] : role === 'CUSTOMER' ? [['Orders',data.orders.length],['Saved pieces',saved.length],['In progress',data.orders.filter(o => ['PENDING','PAYMENT_PENDING','PAID','PROCESSING','SHIPPED'].includes(o.status)).length]] : role === 'STUDENT' ? [['Enrolled courses',data.enrollments.length],['Completed',data.enrollments.filter(e => e.isCompleted).length],['Certificates',data.certificates.length]] : role === 'INSTRUCTOR' ? [['Your courses',data.courses.length],['Course enrollments',data.courses.reduce((n,c) => n+c.enrolledCount,0)],['Upcoming classes',upcoming.length]] : [['Orders',data.metrics?.totalOrders || 0],['Enrollments',data.metrics?.totalEnrollments || 0],['Low-stock variants',data.metrics?.lowStockCount || 0]];
  const empty = (text: string, label: string, route: string) => <div className="dashboard-empty"><p>{text}</p><button className="text-link" onClick={() => onNavigate(route)}>{label}<ArrowUpRight size={16} /></button></div>;
  const updateClass = async (id: string, status: 'COMPLETED' | 'CANCELLED') => {
    setBusyId(id); try { await api.updateTeachingClass(id,status); setRevision(n => n+1); showToast('Class updated.'); } catch(err) { showToast(err instanceof Error ? err.message : 'Could not update class','error'); } finally { setBusyId(''); }
  };
  return <div className="dashboard-layout"><aside className="dashboard-sidebar"><div><span className="eyebrow">Your personal atelier</span><h2>{roleNames[role]}</h2></div><nav aria-label="Dashboard sections">{tabs.map(([id,label]) => <button key={id} className={tab===id?'active':''} onClick={() => setTab(id)}><LayoutDashboard size={16}/>{label}</button>)}</nav><div className="workspace-switch"><span className="eyebrow">Your workspaces</span>{user.roles.map(r => <button key={r} aria-current={role===r?'page':undefined} onClick={() => onNavigate('/dashboard/'+r.toLowerCase())}>{roleNames[r]} <ArrowUpRight size={14}/></button>)}</div><button className="dashboard-signout" onClick={() => signOut().catch(() => showToast('Signed out locally.','info'))}><LogOut size={16}/>Sign out</button></aside><div className="dashboard-content"><header className="dashboard-heading"><div><span className="eyebrow">{role.toLowerCase()} workspace</span><h1>Hello, {user.name.split(' ')[0]}.</h1><p>{titles[role]}</p></div><button className="dashboard-refresh" disabled={loading} onClick={() => setRevision(n=>n+1)} aria-label="Refresh dashboard"><RefreshCw size={16}/></button></header>{error ? <div role="alert" className="dashboard-empty"><p>{error}</p><button className="text-link" onClick={() => setRevision(n=>n+1)}>Try again</button></div> : loading ? <div className="dashboard-empty" role="status">Loading your workspace...</div> : data && <>
    {tab==='overview' && <><div className="dashboard-stats">{stats.map(([label,value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><div className="dashboard-banner"><div><span className="eyebrow">Rooted in culture. Built around you.</span><h2>{role==='INSTRUCTOR'?'Shape the next generation.':role==='STUDENT'?'Make something that matters.':role==='ADMIN'?'Every detail counts.':'Your next statement starts here.'}</h2><button className="brand-button gold" onClick={() => role==='ADMIN'?setTab('manage'):role==='INSTRUCTOR'?setTab('schedule'):onNavigate(role==='STUDENT'?'/academy':'/shop')}>{role==='ADMIN'?'Manage the atelier':role==='INSTRUCTOR'?'View your schedule':role==='STUDENT'?'Explore courses':'Explore the collection'}<ArrowUpRight size={16}/></button></div><img src="/assets/garments/geometric-maze-maxi.jpg" alt="Geometric African print gown" /></div></>}
    {role==='CUSTOMER' && (tab==='overview'||tab==='orders') && <section className="dashboard-panel"><h2>Your orders</h2>{data.orders.length ? <div className="dashboard-table-wrap"><table><thead><tr><th>Order</th><th>Date</th><th>Status</th><th>Total</th><th></th></tr></thead><tbody>{data.orders.map(o=><tr key={o.id}><td>{o.orderNumber}</td><td>{formatDate(o.createdAt)}</td><td>{o.status.replaceAll('_',' ')}</td><td>{money(o.total)}</td><td><button className="text-link" onClick={()=>onNavigate('/orders/'+o.id)}>View<ArrowUpRight size={14}/></button></td></tr>)}</tbody></table></div>:empty('Your wardrobe story is just beginning. Your orders will appear here.','Discover the collection','/shop')}</section>}
    {role==='CUSTOMER' && tab==='saved' && <section className="dashboard-panel"><h2>Saved for you</h2>{saved.length?<div className="grid grid-cols-2 lg:grid-cols-3 gap-5">{saved.map(p=><ProductCard key={p.id} product={p} onSelect={slug=>onNavigate('/shop/'+slug)}/>)}</div>:empty('Save the pieces you love using the heart in the shop.','Find your favourites','/shop')}</section>}
    {role==='STUDENT' && (tab==='overview'||tab==='learning') && <section className="dashboard-panel"><h2>Your learning journey</h2>{data.enrollments.length ? data.enrollments.map(e=><div className="learning-row" key={e.id}><img src={e.courseThumbnail} alt={e.courseTitle}/><div><h3>{e.courseTitle}</h3><p>{e.progressPercent}% complete</p><progress max="100" value={e.progressPercent} aria-label={`${e.courseTitle} progress`}/></div><button className="text-link" onClick={()=>onNavigate('/student/courses/'+e.courseId)}>{e.isCompleted?'Review course':'Continue learning'}<ArrowUpRight size={16}/></button></div>):empty('Start with a course that sparks your creativity.','Explore the academy','/academy')}</section>}
    {role==='STUDENT' && tab==='certificates' && <section className="dashboard-panel"><h2>Earned certificates</h2>{data.certificates.length?data.certificates.map(c=><div className="dashboard-row" key={c.id}><div><h3>{c.courseTitle}</h3><p>{c.grade} / {formatDate(c.issueDate)}</p></div><button className="text-link" onClick={()=>onNavigate('/certificates/'+c.certificateCode)}>View certificate<ArrowUpRight size={16}/></button></div>):empty('Your completed qualifying courses will be celebrated here.','Explore courses','/academy')}</section>}
    {role==='INSTRUCTOR' && (tab==='overview'||tab==='teaching') && <section className="dashboard-panel"><h2>Your courses</h2>{data.courses.length?data.courses.map(c=><div className="learning-row" key={c.id}><img src={c.thumbnail} alt={c.title}/><div><h3>{c.title}</h3><p>{c.enrolledCount} enrollments / {c.modules.length} modules / {c.isPublished?'Published':'Draft'}</p></div><button className="text-link" onClick={()=>onNavigate('/courses/'+c.slug)}>View course<ArrowUpRight size={16}/></button></div>):<div className="dashboard-empty">No courses are assigned to this instructor yet.</div>}</section>}
    {(role==='STUDENT'||role==='INSTRUCTOR') && tab==='schedule' && <section className="dashboard-panel"><h2>{role==='INSTRUCTOR'?'Your teaching schedule':'Your booked classes'}</h2><p className="dashboard-note">Times are shown as scheduled by the atelier.</p>{data.classes.length?data.classes.map(c=><div className="dashboard-row" key={c.id}><div><h3>{c.title}</h3><p>{formatDate(c.date)} / {c.startTime} - {c.endTime}</p><p>{c.status.replaceAll('_',' ')} / {c.enrolledCount} attendees / {c.location}</p></div><div className="flex flex-wrap gap-3">{c.meetingUrl&&c.isOnline&&['SCHEDULED','IN_PROGRESS'].includes(c.status)&&<a className="text-link" href={c.meetingUrl} target="_blank" rel="noreferrer">Join class<ArrowUpRight size={15}/></a>}{role==='INSTRUCTOR'&&['SCHEDULED','IN_PROGRESS'].includes(c.status)&&<button className="text-link" disabled={busyId===c.id} onClick={()=>updateClass(c.id,'COMPLETED')}>Mark completed</button>}</div></div>):empty('No classes are currently scheduled for you.','View live classes','/classes')}<h2 className="mt-8">Mentoring sessions</h2>{data.bookings.length?data.bookings.map(b=><div className="dashboard-row" key={b.id}><div><h3>{b.topic}</h3><p>{role==='INSTRUCTOR'?b.studentName:b.instructorName} / {formatDate(b.date)} / {b.startTime}</p><p>{b.status}</p></div>{b.status==='CONFIRMED'&&b.meetingUrl&&<a className="text-link" href={b.meetingUrl} target="_blank" rel="noreferrer">Join session<ArrowUpRight size={15}/></a>}</div>):<div className="dashboard-empty">No mentoring sessions yet.</div>}</section>}
    {role==='ADMIN' && tab==='manage' && <div className="dashboard-management"><AdminDashboardPage onNavigate={onNavigate}/></div>}
    {tab==='overview' && <section className="dashboard-panel"><h2>From your atelier</h2>{data.notifications.length?data.notifications.slice(0,5).map(n=><div className="dashboard-row" key={n.id}><div><h3>{n.title}</h3><p>{n.message}</p></div>{n.link&&<button className="text-link" onClick={()=>onNavigate(n.link!)}>Open<ArrowUpRight size={16}/></button>}</div>):<p className="dashboard-empty">You're all caught up. New updates will appear here.</p>}</section>}
  </>}</div></div>;
};
